import { type NextPage } from "next";
import Head from "next/head";
import { api } from "@/utils/api";
import { SignInButton, useUser } from "@clerk/nextjs";
import CreatePostWizard from "@/components/create-post-wizard";
import PostView from "@/components/post-view";
import LoadingSpinner from "@/components/loading-spinner";
import Feed from "@/components/feed";

const Home: NextPage = () => {
  const { user, isLoaded: userLoaded, isSignedIn } = useUser();

  api.posts.getAll.useQuery();

  if (!userLoaded) {
    return <div />;
  }

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex justify-center">
        <div className="h-full w-full border-x border-slate-400 md:max-w-2xl">
          <div className="flex border-b border-slate-400 p-4">
            <div className="flex w-full justify-center">
              {isSignedIn ? <CreatePostWizard /> : <SignInButton />}
            </div>
          </div>
          <Feed/>
        </div>
      </main>
    </>
  );
};

export default Home;
