import { type NextPage } from "next";
import Head from "next/head";
import { api } from "@/utils/api";
import { SignInButton, useUser } from "@clerk/nextjs";
import CreatePostWizard from "@/components/create-post-wizard";
import PostView from "@/components/post-view";

const Home: NextPage = () => {
  const { data: postsData, isLoading: postsLoading } =
    api.posts.getAll.useQuery();
  const user = useUser();

  if (postsLoading) {
    return <div>Loading...</div>;
  }

  if (!postsData) {
    return <div>Something went wrong :/</div>;
  }

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex justify-center">
        <div className="h-full w-full border-x border-slate-400 md:max-w-2xl">
          <div className="flex border-b border-slate-400 p-4">
            <div className="flex w-full justify-center">
              {user.isSignedIn ? <CreatePostWizard /> : <SignInButton />}
            </div>
          </div>
          <div className="flex flex-col">
            {[...postsData, ...postsData]?.map((fullPost) => {
              return <PostView key={fullPost.post.id} {...fullPost} />;
            })}
          </div>
        </div>
      </main>
    </>
  );
};

export default Home;
