name: CI

on: [push, pull_request]

env:
  DATABASE_URL: "mysql://0ujqhb7zyo23p82ptilp:pscale_pw_saK3UbVdLIIbpJLWj0IkFNUe8TjK5UJa7OEpPFySMbr@ap-south.connect.psdb.cloud/chirpdb?sslaccept=strict"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: npm install

      - name: Typecheck
        run: npm run typecheck

      - name: Lint
        run: npm run lint

      - name: Print Environment Variable
        run: echo $MY_ENV_VAR